version: "3.7"

services:
  vhry_service_data:
    container_name: vhry_service_data
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - mord_network


networks:
  mord_network:
    name: mord_network
    