version: "3.7"

services:
  app:
    container_name: "go-bank-transfer"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3001:3001
    volumes:
      - ./:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    env_file:
      - .env
    networks:
      - bank
    depends_on:
      - mongodb-primary
      - postgres

  postgres:
    container_name: "postgres"
    image: "postgres:12.2-alpine"
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: bank
    volumes:
      - ./_scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - bank

  mongodb-primary:
    container_name: mongodb-primary
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27017:27017
    networks:
      - bank

networks:
  bank:
